apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: kafka
  name: admin
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operations:
          - Create
          - Describe
          - Read
          - Write
        resource:
          name: connect-cluster-offsets
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Create
          - Describe
          - Read
          - Write
        resource:
          name: connect-cluster-status
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Create
          - Describe
          - Read
          - Write
        resource:
          name: connect-cluster-configs
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Read
        resource:
          name: connect-cluster
          patternType: literal
          type: group
    type: simple    